# https://cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=python

runtime: nodejs18
env: standard
instance_class: F1
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/prod/\1
    upload: dist/prod/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: dist/prod/index.html
    upload: dist/prod/index.html
error_handlers:
  - file: dist/prod/error.html
automatic_scaling:
  min_instances: 0
  max_instances: 1
